/**
 * Writes `src/generated/loaders.js`: every loader in the shell's `src/loaders/`, each kept as the
 * source the shell inlines into its page and run the way the page runs it, so nothing in this
 * App's own build (its transpiler, the React Compiler, its minifier) touches the code a loader
 * starts its worker from. The loaders' colours come with them, from the shell's theme.css.
 *
 * `pnpm run generate` runs it, and so does the Rsbuild config, whenever it loads.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { rspack } from '@rsbuild/core'

import { readAllLoaders, readLoaderTheme } from '../../../apps/shell/scripts/loaders.ts'

const here = dirname(fileURLToPath(import.meta.url))
export const SHELL_ROOT = join(here, '../../../apps/shell')
export const SHELL_LOADERS = join(SHELL_ROOT, 'src/loaders')
const OUT = join(here, '../src/generated')

/** What the gallery calls a loader, where its source says nothing better. */
const TITLES: Record<string, string> = {
  'drill-bit': 'Drill bit',
  'well-log': 'Well log',
  bounce: 'Bounce',
}

function titleOf(name: string, source: string): string {
  // A family's scene says what it is on its first line: `// Pumpjack. A scene for …`.
  const said = /^\/\/ (.+?)\. A scene/.exec(source)
  if (said?.[1] !== undefined) return said[1]
  return TITLES[name] ?? name.replace(/-/g, ' ').replace(/^./, first => first.toUpperCase())
}

/** Minified as the shell minifies it, since this App's own minifier leaves a string alone. */
async function minify(source: string): Promise<string> {
  const { code } = await rspack.experiments.swc.minify(source, {
    compress: true,
    mangle: true,
    format: { comments: false },
  })
  return code
}

export async function generateLoaders(): Promise<void> {
  const { loaders, kits } = readAllLoaders(SHELL_ROOT)
  const theme = readLoaderTheme(SHELL_ROOT)
  const entries = await Promise.all(
    loaders.map(async loader => ({
      name: loader.name,
      title: titleOf(loader.name, loader.source),
      family: loader.kit ?? null,
      source: await minify(loader.source),
    })),
  )
  const kitSources = await Promise.all(
    kits.map(async kit => [kit.name, await minify(kit.source)] as const),
  )

  const js = `// Generated by examples/loaders/scripts/generate-loaders.ts from apps/shell/src/loaders.
// Do not edit: every loader is kept as source and run as the shell's page runs it.

const kitSources = ${JSON.stringify(Object.fromEntries(kitSources))}
const kits = {}
const defined = new Set()

export const theme = ${JSON.stringify(theme)}

export const loaders = ${JSON.stringify(entries.map(({ source: _source, ...entry }) => entry))}

const sources = ${JSON.stringify(Object.fromEntries(entries.map(entry => [entry.name, entry.source])))}

/** Defines \`<name>-loader\`, once, with its family's kit when it has one. */
export function defineLoader(name) {
  const entry = loaders.find(loader => loader.name === name)
  if (entry === undefined || defined.has(name)) return
  defined.add(name)
  let kit
  if (entry.family !== null) {
    kit = kits[entry.family] ?? (kits[entry.family] = new Function(kitSources[entry.family] + '\\nreturn kit')())
  }
  new Function('kit', sources[name])(kit)
}
`
  const dts = `// Generated by examples/loaders/scripts/generate-loaders.ts. Do not edit.

export interface GalleryLoader {
  /** The name \`loader\` in src/mfe.config.ts takes, and the start of its element's tag. */
  readonly name: string
  readonly title: string
  /** The family whose kit it uses, or null for a loader of its own. */
  readonly family: string | null
}

/** Every loader, the ones of their own first, then each family's, by name. */
export declare const loaders: readonly GalleryLoader[]

/** The loaders' colours: the shell's theme.css, for an element with the class \`loader-theme\`. */
export declare const theme: string

/** Defines \`<name>-loader\`, once. */
export declare function defineLoader(name: string): void
`
  mkdirSync(OUT, { recursive: true })
  writeFileSync(join(OUT, 'loaders.js'), js)
  writeFileSync(join(OUT, 'loaders.d.ts'), dts)
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]) {
  await generateLoaders()
}
