/**
 * Neutral definition records. The only public identity field is `id`:
 * `providerId`, `renderOwnerId`, `logicalOwnerId`, `mountId` and `scopeId` must
 * never appear here. The host keeps internal tokens authors never see.
 */

export type DefinitionKind = 'app' | 'widget'

/** The three App-only capability names. Widgets cannot advertise them. */
export const CAPABILITY_NAMES = ['settings', 'help', 'releaseNotes'] as const
export type CapabilityName = (typeof CAPABILITY_NAMES)[number]

export function isCapabilityName(value: unknown): value is CapabilityName {
  return typeof value === 'string' && (CAPABILITY_NAMES as readonly string[]).includes(value)
}

/**
 * An icon *name*, never SVG markup. `{ src }` is the documented escape hatch
 * for a mark the shell set lacks; it renders in an `<img>` and never enters
 * shell DOM as markup.
 */
export type CapabilityIconRef = string | { readonly src: string }

export interface CapabilityDescriptor {
  readonly name: CapabilityName
  readonly label: string
  readonly icon?: CapabilityIconRef
  /** The App-relative route path the shell navigates to when opening it. */
  readonly path: string
}

/**
 * Which build of a container this is. The hash is a content hash of the
 * container's generated sources, and the time is when that hash was first
 * produced — not when the compilation ran — so identical sources describe
 * themselves identically and a rebuild of them is recognisably the same build.
 *
 * Both are optional because a descriptor is produced by a build the reader does
 * not control, and neither ever gates loading: a container that names no build
 * still mounts, it is only harder to report a bug against.
 */
export interface BuildProvenance {
  readonly hash?: string
  readonly time?: string
}

/** Identity and build provenance carried into every diagnostic. */
export interface DefinitionIdentity {
  readonly id: string
  readonly kind: DefinitionKind
  /** Optional; never gates loading, adapter selection or mounting. */
  readonly version?: string
}

/** What one deployable container advertises. Generated by the build plugin. */
export interface ContainerDescriptor {
  readonly manifestUrl: string
  /**
   * The Module Federation container name. Federation vocabulary reaches the
   * neutral shape nowhere else; it is here because a shell has to register the
   * remote under this name before it can fetch anything, so a descriptor
   * without it cannot produce a loadable registry entry — which is the whole
   * reason registry JSON is generated rather than hand-written.
   */
  readonly container: string
  /** The framework contract major this container was built against. */
  readonly contractMajor: number
  readonly definitions: readonly ExportedDefinitionDescriptor[]
  /** Definition id to the generated expose path, for the same reason. */
  readonly entries: Readonly<Record<string, string>>
  readonly build?: BuildProvenance
}

export interface ExportedDefinitionDescriptor extends DefinitionIdentity {
  /** App-only; extracted statically from routes marked with `staticData`. */
  readonly capabilities?: readonly CapabilityDescriptor[]
  /** Widget-only; the published contract, read statically at build time. */
  readonly contract?: PublishedWidgetContract
}

/**
 * What a host may know about a Widget without loading its container.
 *
 * A catalogue has to be rendered before anything is fetched: a host that must
 * load a container to discover what the Widget takes cannot offer it in a
 * picker, and a host that asks for inputs it invented gets them rejected at the
 * provider boundary. So the build publishes the contract it can read — the same
 * schemas the provider validates against, as JSON Schema — and the registry
 * carries it.
 *
 * `inputs` is absent when the build could not read the schema statically. That
 * is a real state, not an error: the Widget still mounts, and a host that wants
 * to offer it has to collect inputs some other way. It is never an empty schema
 * standing in for an unread one, because a host cannot tell those apart.
 */
export interface PublishedWidgetContract {
  /** JSON Schema (draft 2020-12) for the inputs object, when readable. */
  readonly inputs?: JsonSchemaObject
  /** Declared event names, in declaration order. */
  readonly events: readonly string[]
}

/** The subset of JSON Schema the build emits. Values only; no `$ref`. */
export interface JsonSchemaObject {
  readonly [key: string]: JsonSchemaValue
}

export type JsonSchemaValue =
  string | number | boolean | null | readonly JsonSchemaValue[] | JsonSchemaObject

/**
 * A definition ID is also a storage prefix and a CSS scope value, so it is kept
 * to characters that are unambiguous in `<id>:<key>` and in an attribute selector.
 */
const DEFINITION_ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

export function isValidDefinitionId(value: unknown): value is string {
  return typeof value === 'string' && DEFINITION_ID_PATTERN.test(value)
}

export const DEFINITION_ID_RULE =
  'lower-case letters, digits and single hyphens (for example "alert-panel")'
