/**
 * Neutral definition records (§4.1, §4.2).
 *
 * The only public identity field is `id`. `providerId`, `renderOwnerId`,
 * `logicalOwnerId`, `mountId` and `scopeId` must never appear here; the host
 * keeps internal tokens of its own, which authors neither set nor read.
 */

export type DefinitionKind = 'app' | 'widget'

/** The three App-only capability names (§5.10). Widgets cannot advertise them. */
export const CAPABILITY_NAMES = ['settings', 'help', 'releaseNotes'] as const
export type CapabilityName = (typeof CAPABILITY_NAMES)[number]

export function isCapabilityName(value: unknown): value is CapabilityName {
  return typeof value === 'string' && (CAPABILITY_NAMES as readonly string[]).includes(value)
}

/**
 * Capability metadata carries an icon *name*, never SVG markup (§5.10).
 * `{ src }` is the documented escape hatch for a mark the shell set lacks; it
 * renders in an `<img>` and never enters shell DOM as markup.
 */
export type CapabilityIconRef = string | { readonly src: string }

export interface CapabilityDescriptor {
  readonly name: CapabilityName
  readonly label: string
  readonly icon?: CapabilityIconRef
  /** The App-relative route path the shell navigates to when opening it. */
  readonly path: string
}

/** Identity and build provenance carried into every diagnostic (§4.2). */
export interface DefinitionIdentity {
  readonly id: string
  readonly kind: DefinitionKind
  /** Optional; never gates loading, adapter selection or mounting. */
  readonly version?: string
}

/**
 * What one deployable container advertises about itself. Generated by the build
 * plugin (§10.3.1) — nobody hand-writes this.
 */
export interface ContainerDescriptor {
  /** MF2 manifest URL for the container. */
  readonly manifestUrl: string
  /** The framework contract major this container was built against (§11). */
  readonly contractMajor: number
  readonly definitions: readonly ExportedDefinitionDescriptor[]
  readonly build?: {
    readonly hash?: string
    readonly time?: string
  }
}

export interface ExportedDefinitionDescriptor extends DefinitionIdentity {
  /** App-only; extracted statically from routes marked with `staticData` (§5.10). */
  readonly capabilities?: readonly CapabilityDescriptor[]
}

/**
 * A definition ID is a plain string, but it is also a storage prefix and a CSS
 * scope value, so it has to survive both. This keeps it to characters that are
 * unambiguous in `<id>:<key>` and in an attribute selector.
 */
const DEFINITION_ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

export function isValidDefinitionId(value: unknown): value is string {
  return typeof value === 'string' && DEFINITION_ID_PATTERN.test(value)
}

export const DEFINITION_ID_RULE =
  'lower-case letters, digits and single hyphens (for example "alert-panel")'
