/**
 * Neutral definition records. The only public identity field is `id`:
 * `providerId`, `renderOwnerId`, `logicalOwnerId`, `mountId` and `scopeId` must
 * never appear here. The host keeps internal tokens authors never see.
 */

export type DefinitionKind = 'app' | 'widget'

/** The three App-only capability names. Widgets cannot advertise them. */
export const CAPABILITY_NAMES = ['settings', 'help', 'releaseNotes'] as const
export type CapabilityName = (typeof CAPABILITY_NAMES)[number]

export function isCapabilityName(value: unknown): value is CapabilityName {
  return typeof value === 'string' && (CAPABILITY_NAMES as readonly string[]).includes(value)
}

/**
 * An icon *name*, never SVG markup. `{ src }` is the documented escape hatch
 * for a mark the shell set lacks; it renders in an `<img>` and never enters
 * shell DOM as markup.
 */
export type CapabilityIconRef = string | { readonly src: string }

export interface CapabilityDescriptor {
  readonly name: CapabilityName
  readonly label: string
  readonly icon?: CapabilityIconRef
  /** The App-relative route path the shell navigates to when opening it. */
  readonly path: string
}

/** Identity and build provenance carried into every diagnostic. */
export interface DefinitionIdentity {
  readonly id: string
  readonly kind: DefinitionKind
  /** Optional; never gates loading, adapter selection or mounting. */
  readonly version?: string
}

/** What one deployable container advertises. Generated by the build plugin. */
export interface ContainerDescriptor {
  readonly manifestUrl: string
  /** The framework contract major this container was built against. */
  readonly contractMajor: number
  readonly definitions: readonly ExportedDefinitionDescriptor[]
  readonly build?: {
    readonly hash?: string
    readonly time?: string
  }
}

export interface ExportedDefinitionDescriptor extends DefinitionIdentity {
  /** App-only; extracted statically from routes marked with `staticData`. */
  readonly capabilities?: readonly CapabilityDescriptor[]
}

/**
 * A definition ID is also a storage prefix and a CSS scope value, so it is kept
 * to characters that are unambiguous in `<id>:<key>` and in an attribute selector.
 */
const DEFINITION_ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

export function isValidDefinitionId(value: unknown): value is string {
  return typeof value === 'string' && DEFINITION_ID_PATTERN.test(value)
}

export const DEFINITION_ID_RULE =
  'lower-case letters, digits and single hyphens (for example "alert-panel")'
