/** The same sources produce the same bytes, so a watching build never restarts itself (§19). */

import { createHash } from 'node:crypto'
import { chmodSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve, sep } from 'node:path'

export interface GeneratedFile {
  /** Absolute path the file is written to. */
  readonly path: string
  readonly contents: string
  /** A script the deployment runs, so it is written with its execute bits set. */
  readonly executable?: boolean
}

/** Names the integration that wrote the file, which is where a reader goes to change it. */
export function banner(generator: string, alias?: string): string {
  const lines = ['/**', ` * Generated by ${generator}. Do not edit: the next build overwrites it.`]
  if (alias !== undefined) {
    lines.push(' *', ` * Application code imports this module as '${alias}'.`)
  }
  lines.push(' */')
  return lines.join('\n')
}

/** A single-quoted TypeScript string literal. */
export function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`
}

/** A JSON file with stable key order and a trailing newline. */
export function jsonFile(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

/** Joins source blocks with one blank line between them. */
export function joinBlocks(blocks: readonly string[]): string {
  return `${blocks.filter(block => block.trim() !== '').join('\n\n')}\n`
}

/** A POSIX relative specifier from one generated file to a target file. */
export function relativeSpecifier(fromFile: string, toFile: string): string {
  const relativePath = relative(dirname(fromFile), toFile).split(sep).join('/')
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`
}

/** Skipping unchanged files keeps a watching build from restarting itself on its output (§19). */
export function writeGeneratedFiles(files: readonly GeneratedFile[]): readonly GeneratedFile[] {
  const written: GeneratedFile[] = []

  for (const file of files) {
    let current: string | null
    try {
      current = readFileSync(file.path, 'utf8')
    } catch {
      current = null
    }
    if (current !== file.contents) {
      mkdirSync(dirname(file.path), { recursive: true })
      writeFileSync(file.path, file.contents, 'utf8')
      written.push(file)
    }
    // Also when unchanged: a copy that lost the bit would otherwise never get it back.
    if (file.executable === true) chmodSync(file.path, 0o755)
  }

  return written
}

/** Paths hash relative to the generated directory, so another checkout hashes the same (§19). */
export function contentHash(files: readonly GeneratedFile[], baseDir: string): string {
  const hash = createHash('sha256')
  const entries = files
    .map(file => ({ name: relative(baseDir, file.path).split(sep).join('/'), file }))
    .sort((left, right) => (left.name < right.name ? -1 : 1))

  for (const entry of entries) {
    hash.update(`${entry.name}\n${entry.file.contents.length}\n${entry.file.contents}\n`)
  }
  return hash.digest('hex').slice(0, 16)
}

/** Resolves a path inside the build-managed directory. */
export function generatedPath(generatedDir: string, ...segments: readonly string[]): string {
  return resolve(generatedDir, ...segments)
}
