/** The same sources produce the same bytes, so a watching build never restarts itself (§19). */

import { createHash } from 'node:crypto'
import {
  chmodSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmdirSync,
  rmSync,
  statSync,
  writeFileSync,
  type Stats,
} from 'node:fs'
import { dirname, isAbsolute, relative, resolve, sep } from 'node:path'

export interface GeneratedFile {
  /** Absolute path the file is written to. */
  readonly path: string
  readonly contents: string
  /** A script the deployment runs, so it is written with its execute bits set. */
  readonly executable?: boolean
  /** The name it ships under beside the container's assets; absent for a file that stays local. */
  readonly asset?: string
  /**
   * Lists the other files of its run, relative to its own directory. Writing it deletes each file
   * the copy it replaces listed and it does not, so a removed Widget's modules go with it.
   */
  readonly inventory?: boolean
}

/** Where a generated directory lists what the last run wrote into it. */
export const GENERATED_INVENTORY_FILE = '.generated-files.json'

/**
 * The inventory of one run into `generatedDir`. Only what the run generates is listed, so a file
 * the developer keeps there, such as the local runtime configuration, is never deleted.
 */
export function inventoryFile(
  generatedDir: string,
  files: readonly GeneratedFile[],
): GeneratedFile {
  const names = files
    .map(file => posixRelative(generatedDir, file.path))
    .filter(name => !name.startsWith('../') && !isAbsolute(name))
    .sort()
  return {
    path: generatedPath(generatedDir, GENERATED_INVENTORY_FILE),
    contents: jsonFile({ files: names }),
    inventory: true,
  }
}

/** Names the integration that wrote the file, which is where a reader goes to change it. */
export function banner(generator: string, alias?: string): string {
  const lines = ['/**', ` * Generated by ${generator}. Do not edit: the next build overwrites it.`]
  if (alias !== undefined) {
    lines.push(' *', ` * Application code imports this module as '${alias}'.`)
  }
  lines.push(' */')
  return lines.join('\n')
}

/** A single-quoted TypeScript string literal. */
export function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`
}

/** A JSON file with stable key order and a trailing newline. */
export function jsonFile(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

/** Joins source blocks with one blank line between them. */
export function joinBlocks(blocks: readonly string[]): string {
  return `${blocks.filter(block => block.trim() !== '').join('\n\n')}\n`
}

/** `relative()` answers in the host's separator; every path a person or a specifier reads is POSIX. */
export function posixRelative(from: string, to: string): string {
  return relative(from, to).split(sep).join('/')
}

/** A POSIX relative specifier from one generated file to a target file. */
export function relativeSpecifier(fromFile: string, toFile: string): string {
  const relativePath = posixRelative(dirname(fromFile), toFile)
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`
}

/** Skipping unchanged files keeps a watching build from restarting itself on its output (§19). */
export function writeGeneratedFiles(files: readonly GeneratedFile[]): readonly GeneratedFile[] {
  return createGeneratedFileWriter()(files)
}

interface WrittenFile {
  readonly contents: string
  readonly size: number
  readonly mtimeMs: number
}

/**
 * For a build that writes before every compile: a file this writer wrote, which still has the
 * size and modification time it left it with, is compared in memory instead of read back. One
 * deleted or edited since is read and rewritten like any other.
 */
export function createGeneratedFileWriter(): (
  files: readonly GeneratedFile[],
) => readonly GeneratedFile[] {
  const known = new Map<string, WrittenFile>()

  return files => {
    const written: GeneratedFile[] = []
    const stale: { readonly path: string; readonly root: string }[] = []

    for (const file of files) {
      let stats = statOf(file.path)
      if (stats === null || !holds(file, stats, known.get(file.path))) {
        // Read before it is replaced: an unchanged inventory lists nothing to delete.
        if (file.inventory === true && stats !== null) stale.push(...unlisted(file))
        mkdirSync(dirname(file.path), { recursive: true })
        writeFileSync(file.path, file.contents, 'utf8')
        written.push(file)
        stats = statSync(file.path)
      }
      // Also when unchanged: a copy that lost the bit would otherwise never get it back.
      if (file.executable === true) chmodSync(file.path, 0o755)

      known.set(file.path, { contents: file.contents, size: stats.size, mtimeMs: stats.mtimeMs })
    }

    for (const { path, root } of stale) {
      removeGeneratedFile(path, root)
      known.delete(path)
    }

    return written
  }
}

/** The files the inventory on disk lists and `inventory` no longer does, with their directory. */
function unlisted(inventory: GeneratedFile): { readonly path: string; readonly root: string }[] {
  const root = dirname(inventory.path)
  const current = new Set(listedIn(inventory.contents))

  return listedIn(readFileSync(inventory.path, 'utf8'))
    .filter(name => !current.has(name))
    .map(name => resolve(root, name))
    .filter(path => path !== inventory.path && isInside(root, path))
    .map(path => ({ path, root }))
}

/** An inventory that cannot be read lists nothing, so nothing is deleted on its account. */
function listedIn(contents: string): readonly string[] {
  let parsed: unknown
  try {
    parsed = JSON.parse(contents)
  } catch {
    return []
  }
  if (typeof parsed !== 'object' || parsed === null) return []
  const files: unknown = (parsed as { files?: unknown }).files
  if (!Array.isArray(files)) return []
  return files.filter((name): name is string => typeof name === 'string')
}

function isInside(directory: string, path: string): boolean {
  const name = relative(directory, path)
  return name !== '' && !name.startsWith(`..${sep}`) && name !== '..' && !isAbsolute(name)
}

/** Removes the file, then each directory below `root` it leaves empty. */
function removeGeneratedFile(path: string, root: string): void {
  if (statOf(path)?.isFile() !== true) return
  rmSync(path)
  let directory = dirname(path)
  while (isInside(root, directory) && isEmptyDirectory(directory)) {
    rmdirSync(directory)
    directory = dirname(directory)
  }
}

function isEmptyDirectory(path: string): boolean {
  return statOf(path)?.isDirectory() === true && readdirSync(path).length === 0
}

/** Whether the file on disk already holds these contents, answered from memory when it can be. */
function holds(file: GeneratedFile, onDisk: Stats, last: WrittenFile | undefined): boolean {
  if (last !== undefined && last.size === onDisk.size && last.mtimeMs === onDisk.mtimeMs) {
    return last.contents === file.contents
  }
  return readFileSync(file.path, 'utf8') === file.contents
}

function statOf(path: string): Stats | null {
  try {
    return statSync(path)
  } catch {
    return null
  }
}

/** Paths hash relative to the generated directory, so another checkout hashes the same (§19). */
export function contentHash(files: readonly GeneratedFile[], baseDir: string): string {
  const hash = createHash('sha256')
  const entries = files
    .map(file => ({ name: posixRelative(baseDir, file.path), file }))
    .sort((left, right) => (left.name < right.name ? -1 : 1))

  for (const entry of entries) {
    hash.update(`${entry.name}\n${entry.file.contents.length}\n${entry.file.contents}\n`)
  }
  return hash.digest('hex').slice(0, 16)
}

/** Resolves a path inside the build-managed directory. */
export function generatedPath(generatedDir: string, ...segments: readonly string[]): string {
  return resolve(generatedDir, ...segments)
}
