/**
 * Emitting generated files.
 *
 * Everything the build writes is deterministic: the same sources produce the
 * same bytes, so a generated file never shows up in a diff because two machines
 * disagreed about key order or quoting. The TypeScript the generator writes is
 * already in the house style — no semicolons, single quotes, trailing commas —
 * because a developer will read it the first time something goes wrong, and
 * running a formatter over build output is not a step anyone remembers.
 */

import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve, sep } from 'node:path'

export interface GeneratedFile {
  /** Absolute path the file is written to. */
  readonly path: string
  readonly contents: string
}

/** The banner every generated module carries. */
export function banner(alias?: string): string {
  const lines = [
    '/**',
    ' * Generated by @company/mfe-rspack. Do not edit: the next build overwrites it.',
  ]
  if (alias !== undefined) {
    lines.push(' *', ` * Application code imports this module as '${alias}'.`)
  }
  lines.push(' */')
  return lines.join('\n')
}

/** A single-quoted TypeScript string literal. */
export function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`
}

/** A JSON file with stable key order and a trailing newline. */
export function jsonFile(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

/** Joins source blocks with one blank line between them. */
export function joinBlocks(blocks: readonly string[]): string {
  return `${blocks.filter(block => block.trim() !== '').join('\n\n')}\n`
}

/** A POSIX relative specifier from one generated file to a target file. */
export function relativeSpecifier(fromFile: string, toFile: string): string {
  const relativePath = relative(dirname(fromFile), toFile).split(sep).join('/')
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`
}

/**
 * Writes the files that changed. Skipping unchanged files keeps a watching
 * build from restarting itself on its own output.
 */
export function writeGeneratedFiles(files: readonly GeneratedFile[]): readonly GeneratedFile[] {
  const written: GeneratedFile[] = []

  for (const file of files) {
    let current: string | null = null
    try {
      current = readFileSync(file.path, 'utf8')
    } catch {
      current = null
    }
    if (current === file.contents) continue

    mkdirSync(dirname(file.path), { recursive: true })
    writeFileSync(file.path, file.contents, 'utf8')
    written.push(file)
  }

  return written
}

/**
 * A content hash of everything the build generated. It changes when the
 * container's shape changes and not otherwise, which is what makes it useful in
 * a diagnostic: two reports carrying the same hash describe the same build.
 */
export function contentHash(files: readonly GeneratedFile[]): string {
  const hash = createHash('sha256')
  for (const file of [...files].sort((left, right) => (left.path < right.path ? -1 : 1))) {
    hash.update(`${file.path}\n${file.contents.length}\n${file.contents}\n`)
  }
  return hash.digest('hex').slice(0, 16)
}

/** Resolves a path inside the build-managed directory. */
export function generatedPath(generatedDir: string, ...segments: readonly string[]): string {
  return resolve(generatedDir, ...segments)
}
