/**
 * The `author` preset: for MFE Apps and Widgets, that is the code in
 * `examples/*` and in every product repository that ships an MFE.
 *
 * An author's constraints are the mirror image of the framework's. Application
 * state libraries are fine, and zustand is expected. Reaching into framework
 * internals, owning the React root, shipping a telemetry SDK or writing raw Web
 * Storage are not, because each of them turns a fragment into something that
 * behaves like the whole page.
 */

import type { Linter } from 'eslint'
import queryPlugin from '@tanstack/eslint-plugin-query'
import routerPlugin from '@tanstack/eslint-plugin-router'
import {
  ALL_FILES,
  TS_FILES,
  asConfigs,
  asyncCorrectness,
  eslintRecommended,
  languageConfig,
  maintainability,
  mfePlugin,
  reactCorrectness,
  tseslint,
  typeSafety,
  withFiles,
} from './shared.ts'
import {
  AUTHOR_FRAMEWORK_PATHS,
  AUTHOR_FRAMEWORK_PATTERNS,
  AUTHOR_TELEMETRY_PATTERNS,
  restrictedImports,
  type RestrictedPath,
  type RestrictedPattern,
} from './restricted-imports.ts'

/** Where TanStack Router code lives by default. */
export const DEFAULT_ROUTER_FILES: readonly string[] = [
  '**/routes/**/*.{ts,tsx}',
  '**/*.route.{ts,tsx}',
  '**/*.routes.{ts,tsx}',
  '**/router.{ts,tsx}',
  '**/routeTree.gen.ts',
]

export interface AuthorPresetOptions {
  /** Root directory for the type-aware program. Defaults to the ESLint CWD. */
  readonly tsconfigRootDir?: string | undefined
  /** Files the preset applies to. Defaults to every TypeScript file. */
  readonly files?: readonly string[] | undefined
  /**
   * Widget-owned sources. `mfe/no-widget-global-effects` reports only inside
   * these globs; with none configured it is inert, because Widget ownership is
   * declared, never inferred from a file name.
   */
  readonly widgetScopes?: readonly string[] | undefined
  /**
   * Files allowed to touch Web Storage directly, normally only a documented
   * shell override bootstrap.
   */
  readonly storageAllowedScopes?: readonly string[] | undefined
  /** Where the TanStack Router rules apply. */
  readonly routerFiles?: readonly string[] | undefined
  /** Extra restricted paths appended to the author boundary. */
  readonly extraRestrictedPaths?: readonly RestrictedPath[] | undefined
  /** Extra restricted patterns appended to the author boundary. */
  readonly extraRestrictedPatterns?: readonly RestrictedPattern[] | undefined
}

/** Builds the `author` preset. */
export function author(options: AuthorPresetOptions = {}): Linter.Config[] {
  const files = options.files ?? TS_FILES
  const routerFiles = options.routerFiles ?? DEFAULT_ROUTER_FILES
  const widgetScopes = options.widgetScopes ?? []
  const storageAllowedScopes = options.storageAllowedScopes ?? []
  const extraPaths = options.extraRestrictedPaths ?? []
  const extraPatterns = options.extraRestrictedPatterns ?? []

  return [
    { ...eslintRecommended(), files: [...ALL_FILES] },
    languageConfig({ tsconfigRootDir: options.tsconfigRootDir, files }),
    ...withFiles(
      asConfigs(tseslint.configs.recommendedTypeChecked),
      files,
      'mfe/typescript-recommended',
    ),
    asyncCorrectness,
    typeSafety,
    maintainability,
    ...reactCorrectness(files),
    ...withFiles(asConfigs(queryPlugin.configs['flat/recommended']), files, 'mfe/tanstack-query'),
    ...withFiles(
      asConfigs(routerPlugin.configs['flat/recommended']),
      routerFiles,
      'mfe/tanstack-router',
    ),
    {
      name: 'mfe/author/boundaries',
      files: [...files],
      rules: {
        // zustand and the other application state libraries are deliberately
        // absent from this list: an MFE owns its own state. What it may not own
        // is the framework's internals, the React root, or a telemetry SDK.
        '@typescript-eslint/no-restricted-imports': restrictedImports(
          [...AUTHOR_FRAMEWORK_PATHS, ...extraPaths],
          [...AUTHOR_FRAMEWORK_PATTERNS, ...AUTHOR_TELEMETRY_PATTERNS, ...extraPatterns],
        ),
      },
    },
    {
      name: 'mfe/author/rules',
      files: [...files],
      plugins: { mfe: mfePlugin },
      rules: {
        'mfe/no-global-patching': 'error',
        'mfe/stable-definitions': 'error',
        'mfe/no-raw-storage': ['error', { allowedScopes: [...storageAllowedScopes] }],
        'mfe/no-widget-global-effects': ['error', { widgetScopes: [...widgetScopes] }],
      },
    },
    {
      name: 'mfe/author/generated',
      files: ['**/routeTree.gen.ts', '**/src/generated/**/*.{ts,tsx}'],
      rules: {
        // Generated by the router plugin; reviewing it is the generator's job,
        // not the author's.
        '@typescript-eslint/no-unused-vars': 'off',
        '@typescript-eslint/consistent-type-imports': 'off',
        '@typescript-eslint/no-explicit-any': 'off',
      },
    },
    {
      name: 'mfe/author/tests',
      files: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}', '**/__tests__/**/*.{ts,tsx}'],
      rules: {
        'mfe/no-global-patching': 'off',
        'mfe/no-raw-storage': 'off',
        '@typescript-eslint/no-non-null-assertion': 'off',
        '@typescript-eslint/no-unsafe-assignment': 'off',
      },
    },
  ]
}
