/**
 * The primitives `build-scenes.mjs` drafts the ten scenes with: elements with the fields
 * Excalidraw's own file format requires, text measured with Excalifont's real advance widths,
 * and arrows whose points reach the shapes they are bound to.
 *
 * The committed `.excalidraw` files are the source of truth. This only exists because ten
 * scenes drawn by hand would not share one grid, one palette or one text size.
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const scenesDir = join(fileURLToPath(new URL('..', import.meta.url)), 'scenes')

/**
 * Advance widths at font size 100, measured in Chromium with the font files
 * `@excalidraw/excalidraw` ships (`dist/prod/fonts/Excalifont/…a88b72a2….woff2`), which is the
 * same measurement Excalidraw makes when it lays a text element out. Anything missing falls
 * back to the width of `o`.
 */
const EXCALIFONT = {
  ' ': 40,
  '!': 31.4,
  '"': 37.1,
  '#': 78.3,
  $: 72.1,
  '%': 92.8,
  '&': 71.8,
  "'": 21.8,
  '(': 44.1,
  ')': 40.2,
  '*': 52.5,
  '+': 55,
  ',': 25.7,
  '-': 41.1,
  '.': 27.4,
  '/': 56.1,
  0: 66.4,
  1: 42.7,
  2: 70,
  3: 60.8,
  4: 58.5,
  5: 61.8,
  6: 64,
  7: 55.8,
  8: 63.6,
  9: 62.9,
  ':': 26.4,
  ';': 29.8,
  '<': 55,
  '=': 55,
  '>': 55,
  '?': 46.6,
  '@': 82.9,
  A: 67.6,
  B: 76.1,
  C: 62.9,
  D: 78,
  E: 70.7,
  F: 66.1,
  G: 78,
  H: 57.3,
  I: 54.5,
  J: 56.9,
  K: 61.3,
  L: 54.3,
  M: 76.6,
  N: 63.2,
  O: 76.7,
  P: 69.8,
  Q: 76.8,
  R: 73.6,
  S: 62.2,
  T: 85.7,
  U: 73,
  V: 59.2,
  W: 78.6,
  X: 62.8,
  Y: 56.4,
  Z: 83.2,
  '[': 47.2,
  '\\': 58.9,
  ']': 49.7,
  '^': 51,
  _: 67,
  '`': 60,
  a: 57.6,
  b: 55.5,
  c: 50.4,
  d: 60.5,
  e: 53.7,
  f: 49.7,
  g: 55.5,
  h: 56.7,
  i: 24.4,
  j: 32.8,
  k: 53.3,
  l: 22.5,
  m: 66.3,
  n: 52.6,
  o: 60,
  p: 53.7,
  q: 53.9,
  r: 41.2,
  s: 54.3,
  t: 55.3,
  u: 54.8,
  v: 52.5,
  w: 69.3,
  x: 59.1,
  y: 53,
  z: 57.2,
  '{': 50.4,
  '|': 29.9,
  '}': 54.4,
  '~': 66.9,
  '—': 93.5,
  '·': 20,
  '’': 30.4,
  '…': 70.9,
}

/** Comic Shanns is monospaced at 0.55em, measured the same way. */
const COMIC_ADVANCE = 55

/** Excalidraw's `FONT_FAMILY`; only these two are used, and it embeds both. */
export const FONT = { hand: 5, mono: 8 }

/** Excalidraw's own line height for both faces. */
const LINE_HEIGHT = 1.25

/** What Excalidraw leaves between a container's edge and the text bound inside it. */
const BOUND_TEXT_PADDING = 5

export const STROKE = {
  ink: '#1e1e1e',
  muted: '#868e96',
  red: '#e03131',
  blue: '#1971c2',
  green: '#2f9e44',
}

/**
 * One hue per concern, the same in all ten diagrams, all from Excalidraw's own palette.
 * A diagram in which a colour carries meaning says so in a legend.
 */
export const FILL = {
  shell: '#ffec99',
  container: '#a5d8ff',
  generated: '#d0bfff',
  storage: '#b2f2bb',
  network: '#ffd8a8',
  page: '#f1f3f5',
  failure: '#ffc9c9',
  none: 'transparent',
}

export const LEGEND_LABELS = {
  shell: 'the shell (the host page)',
  container: 'a container (an App, or Widgets)',
  generated: 'generated by the build',
  storage: 'storage',
  network: 'network and API',
  page: 'the browser document',
  failure: 'a failure path',
}

/** Base62, the alphabet `fractional-indexing` orders element `index` values in. */
const DIGITS = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'

function fractionalIndex(position) {
  if (position < 62) return `a${DIGITS[position]}`
  const rest = position - 62
  if (rest < 62 * 62) return `b${DIGITS[Math.floor(rest / 62)]}${DIGITS[rest % 62]}`
  const deeper = rest - 62 * 62
  return `c${DIGITS[Math.floor(deeper / 3844)]}${DIGITS[Math.floor(deeper / 62) % 62]}${DIGITS[deeper % 62]}`
}

/** One line's width, in the same units Excalidraw measures a text element in. */
export function lineWidth(line, fontSize, family) {
  if (family === FONT.mono) return (line.length * COMIC_ADVANCE * fontSize) / 100
  let total = 0
  for (const character of line) total += EXCALIFONT[character] ?? EXCALIFONT['o']
  return (total * fontSize) / 100
}

export function measureText(text, fontSize, family) {
  const lines = String(text).split('\n')
  return {
    width: Math.max(...lines.map(line => lineWidth(line, fontSize, family))),
    height: lines.length * fontSize * LINE_HEIGHT,
  }
}

/** Deterministic, because a random seed would change the drawing on every re-draft. */
function seededIntegers(name) {
  let state = 0
  for (const character of name) state = (state * 31 + character.charCodeAt(0)) >>> 0
  return () => {
    state = (state * 1_664_525 + 1_013_904_223) >>> 0
    return state % 2_147_483_647
  }
}

/** A day Excalidraw will not redraw anything over; a real clock would break re-drafting. */
const UPDATED = 1_735_689_600_000

export function createScene(name) {
  const elements = []
  const nextInteger = seededIntegers(name)
  let counter = 0
  let groupStack = []

  const identify = kind => {
    counter += 1
    return `${name}-${kind}-${String(counter).padStart(2, '0')}`
  }

  const common = () => ({
    angle: 0,
    strokeColor: STROKE.ink,
    backgroundColor: FILL.none,
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 100,
    groupIds: [...groupStack],
    frameId: null,
    roundness: null,
    seed: nextInteger(),
    version: 1,
    versionNonce: nextInteger(),
    isDeleted: false,
    boundElements: null,
    updated: UPDATED,
    link: null,
    locked: false,
    index: null,
  })

  const push = element => {
    elements.push(element)
    return element
  }

  /** A free-standing label: the text element measures itself, so nothing ever clips. */
  function text(options) {
    const {
      x,
      y,
      text: body,
      size = 16,
      family = FONT.hand,
      color = STROKE.ink,
      align = 'left',
      opacity = 100,
    } = options
    const { width, height } = measureText(body, size, family)

    return push({
      ...common(),
      id: options.id ?? identify('text'),
      type: 'text',
      x: align === 'center' ? x - width / 2 : align === 'right' ? x - width : x,
      y,
      width,
      height,
      opacity,
      strokeColor: color,
      text: String(body),
      originalText: String(body),
      fontSize: size,
      fontFamily: family,
      textAlign: 'left',
      verticalAlign: 'top',
      containerId: null,
      autoResize: true,
      lineHeight: LINE_HEIGHT,
    })
  }

  /** A shape with its label bound inside it, which is what makes the two move together. */
  function shape(type, options) {
    const {
      x,
      y,
      w,
      h,
      fill = FILL.none,
      stroke = STROKE.ink,
      label,
      size = 16,
      family = FONT.hand,
      dashed = false,
      sharp = false,
      strokeWidth = 2,
      opacity = 100,
    } = options

    const id = options.id ?? identify(type)
    const container = push({
      ...common(),
      id,
      type,
      x,
      y,
      width: w,
      height: h,
      backgroundColor: fill,
      strokeColor: stroke,
      strokeWidth,
      opacity,
      strokeStyle: dashed ? 'dashed' : 'solid',
      roundness: sharp || type === 'diamond' ? null : { type: 3 },
    })

    if (label !== undefined && label !== '') {
      const { width, height } = measureText(label, size, family)
      const bound = push({
        ...common(),
        id: `${id}-label`,
        type: 'text',
        x: x + (w - width) / 2,
        y: y + (h - height) / 2,
        width,
        height,
        opacity,
        text: String(label),
        originalText: String(label),
        fontSize: size,
        fontFamily: family,
        textAlign: 'center',
        verticalAlign: 'middle',
        containerId: id,
        autoResize: false,
        lineHeight: LINE_HEIGHT,
      })
      container.boundElements = [{ type: 'text', id: bound.id }]

      const needed = width + BOUND_TEXT_PADDING * 2
      if (needed > w) {
        throw new Error(
          `${name}: the label ${JSON.stringify(label)} needs ${Math.ceil(needed)}px but its ${type} is ${String(w)}px wide`,
        )
      }
      if (height + BOUND_TEXT_PADDING * 2 > h) {
        throw new Error(
          `${name}: the label ${JSON.stringify(label)} needs ${Math.ceil(height + 10)}px of height but its ${type} is ${String(h)}px tall`,
        )
      }
    }

    return container
  }

  const box = options => shape('rectangle', options)
  const ellipse = options => shape('ellipse', options)
  const diamond = options => shape('diamond', options)

  /** The point an arrow leaves or meets a shape at, pushed `gap` px clear of the edge. */
  function anchor(target, gap) {
    const { shape: element, side, at = 0.5 } = target
    const { x, y, width, height } = element

    if (side === 'right') return [x + width + gap, y + height * at]
    if (side === 'left') return [x - gap, y + height * at]
    if (side === 'top') return [x + width * at, y - gap]
    if (side === 'bottom') return [x + width * at, y + height + gap]
    throw new Error(`${name}: ${String(side)} is not a side of a shape`)
  }

  function bind(element, arrowId) {
    element.boundElements = [...(element.boundElements ?? []), { type: 'arrow', id: arrowId }]
  }

  /**
   * `from` and `to` name a shape and the side the arrow leaves or meets it on, so a moved box
   * takes its arrows with it. `elbow` bends the path once, which is what keeps a long arrow
   * off the shapes it passes.
   */
  function arrow(options) {
    const {
      from,
      to,
      gap = 8,
      elbow = null,
      via = null,
      label,
      size = 14,
      family = FONT.hand,
      color = STROKE.ink,
      dashed = false,
      dotted = false,
      startArrowhead = null,
      endArrowhead = 'arrow',
      labelOffset = 0,
      labelDx = 0,
      sharp,
    } = options

    const start = anchor(from, gap)
    const end = anchor(to, gap)

    let points
    if (via !== null) points = [start, ...via, end]
    else if (elbow === 'h') {
      const middle = via ?? (start[0] + end[0]) / 2
      points = [start, [middle, start[1]], [middle, end[1]], end]
    } else if (elbow === 'v') {
      const middle = (start[1] + end[1]) / 2
      points = [start, [start[0], middle], [end[0], middle], end]
    } else points = [start, end]

    const id = options.id ?? identify('arrow')
    const xs = points.map(point => point[0])
    const ys = points.map(point => point[1])

    const element = push({
      ...common(),
      id,
      type: 'arrow',
      x: start[0],
      y: start[1],
      width: Math.max(...xs) - Math.min(...xs),
      height: Math.max(...ys) - Math.min(...ys),
      strokeColor: color,
      strokeStyle: dotted ? 'dotted' : dashed ? 'dashed' : 'solid',
      // Excalidraw's proportional radius is a fraction of the segment, so a long
      // elbow rounds into a loop; a bent path is drawn with sharp corners instead.
      roundness: (sharp ?? points.length > 2) ? null : { type: 2 },
      points: points.map(point => [point[0] - start[0], point[1] - start[1]]),
      lastCommittedPoint: null,
      startBinding: { elementId: from.shape.id, focus: 0, gap },
      endBinding: { elementId: to.shape.id, focus: 0, gap },
      startArrowhead,
      endArrowhead,
      elbowed: false,
    })

    bind(from.shape, id)
    bind(to.shape, id)

    if (label !== undefined && label !== '') {
      const middle = midpoint(points)
      text({
        x: middle[0] + labelDx,
        y: middle[1] - measureText(label, size, family).height / 2 + labelOffset,
        text: label,
        size,
        family,
        color,
        align: 'center',
      })
    }

    return element
  }

  /** The centre of the longest segment: where a label sits clear of both ends. */
  function midpoint(points) {
    let best = 0
    let bestLength = -1
    for (let index = 0; index < points.length - 1; index += 1) {
      const length =
        Math.abs(points[index + 1][0] - points[index][0]) +
        Math.abs(points[index + 1][1] - points[index][1])
      if (length > bestLength) {
        bestLength = length
        best = index
      }
    }
    return [
      (points[best][0] + points[best + 1][0]) / 2,
      (points[best][1] + points[best + 1][1]) / 2,
    ]
  }

  /** The diagram's own name, top-left, the same size in every scene. */
  function title(heading, subtitle) {
    text({ x: 0, y: 0, text: heading, size: 28 })
    if (subtitle !== undefined) {
      text({ x: 0, y: 40, text: subtitle, size: 16, color: STROKE.muted })
    }
  }

  /** A swatch and a line of text per entry, in one column. */
  function legend(options) {
    const { x, y, entries, size = 14, heading = 'What the colours mean' } = options
    text({ x, y, text: heading, size, color: STROKE.muted })

    entries.forEach((entry, position) => {
      const top = y + 24 + position * 24
      box({ x, y: top, w: 18, h: 16, fill: entry.fill, sharp: true, strokeWidth: 1 })
      text({ x: x + 28, y: top, text: entry.label, size })
    })
  }

  /** Everything drawn inside the callback shares one group id, and stays contiguous. */
  function group(draw) {
    const id = identify('group')
    groupStack = [...groupStack, id]
    try {
      draw()
    } finally {
      groupStack = groupStack.slice(0, -1)
    }
    return id
  }

  async function write() {
    elements.forEach((element, position) => {
      element.index = fractionalIndex(position)
    })

    const scene = {
      type: 'excalidraw',
      version: 2,
      source: 'mfe-framework/tools/diagrams',
      elements,
      appState: { gridSize: null, viewBackgroundColor: '#ffffff' },
      files: {},
    }

    const file = join(scenesDir, `${name}.excalidraw`)
    await mkdir(dirname(file), { recursive: true })
    await writeFile(file, `${JSON.stringify(scene, null, 2)}\n`, 'utf8')
    return file
  }

  return { arrow, box, diamond, ellipse, elements, group, legend, text, title, write }
}
