/**
 * Release gate for the browser support policy: prints the report, writes the
 * checked-in artifacts, and exits non-zero when measured coverage falls below
 * the target.
 */

import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { loadSupportData, type SupportData } from './caniuse.ts'
import { computeMatrix, COVERAGE_TARGET_PERCENT, type BrowserMatrix } from './matrix.ts'
import { REQUIRED_FEATURES, type RequiredFeature } from './required-features.ts'

export const ARTIFACT_FILENAME = 'browser-matrix.json'
export const BROWSERSLISTRC_FILENAME = '.browserslistrc'

interface ReportMeta {
  readonly generatedAt: string
  readonly caniuseVersion: string
  readonly browserslistVersion: string
}

/** Rounds to 4 decimals so the checked-in artifact does not churn on float noise. */
function round(value: number): number {
  return Number(value.toFixed(4))
}

function percent(value: number, digits = 2): string {
  return `${value.toFixed(digits)}%`
}

/**
 * The checked-in `browser-matrix.json`. This builder is its only definition, so
 * the artifact and its type cannot drift.
 */
function buildArtifact(
  matrix: BrowserMatrix,
  meta: ReportMeta,
  features: readonly RequiredFeature[],
) {
  return {
    generatedAt: meta.generatedAt,
    generatedBy: 'pnpm browser-matrix (tools/browser-matrix)',
    caniuseLiteVersion: meta.caniuseVersion,
    browserslistVersion: meta.browserslistVersion,
    coverageTargetPercent: matrix.target,
    measuredCoveragePercent: round(matrix.coverage),
    meetsTarget: matrix.meetsTarget,
    dataCeilingPercent: round(matrix.totalUsage),
    requiredFeatures: features,
    appliedFeatureIds: matrix.featureIds,
    unresolvedFeatureIds: matrix.unresolvedFeatureIds,
    minimumVersions: Object.fromEntries(matrix.floors.map(floor => [floor.browser, floor.version])),
    browserslistQuery: matrix.query,
    supportedVersionCount: matrix.supportedVersions.length,
    excludedBrowsers: matrix.excluded.map(entry => ({
      browser: entry.browser,
      latestReleased: entry.latestReleased,
      usagePercent: round(entry.usage),
      missing: entry.missingFeatures.map(feature => ({ id: feature.id, support: feature.support })),
    })),
  }
}

function renderBrowserslistrc(matrix: BrowserMatrix, meta: ReportMeta): string {
  // Each line of a browserslist config is its own query and the lines are
  // OR-ed, so one `>=` floor per browser is exactly the supported union.
  return [
    '# Generated by `pnpm browser-matrix`: the browser support policy.',
    '# DO NOT HAND-EDIT: rerun `pnpm browser-matrix` instead.',
    '#',
    '# These floors are the intersection of the required native features in',
    '# tools/browser-matrix/src/required-features.ts — chiefly CSS @scope, for',
    '# which no fallback ships.',
    `# caniuse-lite ${meta.caniuseVersion} · browserslist ${meta.browserslistVersion}`,
    `# measured aggregate global usage: ${percent(matrix.coverage, 4)} (target ${percent(matrix.target, 0)})`,
    `# generation timestamp and full detail: tools/browser-matrix/${ARTIFACT_FILENAME}`,
    '',
    ...matrix.floors.map(floor => `${floor.browser} >= ${floor.version}`),
    '',
  ].join('\n')
}

/** Pads every column but the last, so the report reads as a table. */
function table(rows: readonly (readonly string[])[]): string[] {
  const widths: number[] = []
  for (const row of rows) {
    row.forEach((cell, index) => {
      widths[index] = Math.max(widths[index] ?? 0, cell.length)
    })
  }
  return rows.map(row =>
    row
      .map((cell, index) => (index === row.length - 1 ? cell : cell.padEnd(widths[index] ?? 0)))
      .join('  ')
      .trimEnd(),
  )
}

function renderShortfall(matrix: BrowserMatrix): string[] {
  const losses = [
    ...matrix.excluded.map(entry => ({
      label: `${entry.browser} (all versions)`,
      usage: entry.usage,
      why:
        entry.missingFeatures.map(feature => `${feature.id}=${feature.support}`).join(', ') ||
        'no released versions in the dataset',
    })),
    ...matrix.floors
      .filter(floor => floor.usageBelowFloor > 0)
      .map(floor => ({
        label: `${floor.browser} < ${floor.version}`,
        usage: floor.usageBelowFloor,
        why: 'released before the required feature floor',
      })),
  ]
    .filter(loss => loss.usage > 0)
    .sort((a, b) => b.usage - a.usage)

  return [
    `FAIL: coverage ${percent(matrix.coverage, 4)} is ${percent(matrix.target - matrix.coverage, 4)} short of the ${percent(matrix.target, 0)} target.`,
    '',
    'Where the missing usage sits:',
    ...table(losses.map(loss => [`  ${loss.label}`, percent(loss.usage), loss.why])),
    '',
    'The feature floor and the coverage target are jointly unsatisfiable on this data. ' +
      'Either the target moves, a fallback ships for the feature that costs the most usage, ' +
      'or the release is gated as-is.',
  ]
}

function renderReport(
  matrix: BrowserMatrix,
  meta: ReportMeta,
  features: readonly RequiredFeature[],
): string {
  return [
    'Browser support matrix',
    '',
    ...table([
      ['  caniuse-lite', meta.caniuseVersion],
      ['  browserslist', meta.browserslistVersion],
      ['  generated', meta.generatedAt],
    ]),
    '',
    'Required native features (a browser must fully support every one):',
    ...table(
      features.map(feature => [
        `  ${feature.id}`,
        matrix.unresolvedFeatureIds.includes(feature.id) ? '[UNRESOLVED] ' : '',
        feature.reason,
      ]),
    ),
    ...(matrix.unresolvedFeatureIds.length === 0
      ? []
      : [
          '',
          `  ! Not present in caniuse-lite ${meta.caniuseVersion} and therefore NOT applied:`,
          ...matrix.unresolvedFeatureIds.map(id => `    ${id}`),
        ]),
    '',
    `Supported matrix: ${matrix.floors.length} browsers, ${matrix.supportedVersions.length} released versions`,
    ...table([
      ['  browser', 'floor', 'usage', 'lost below floor'],
      ...[...matrix.floors]
        .sort((a, b) => b.usage - a.usage)
        .map(floor => [
          `  ${floor.browser}`,
          floor.version,
          percent(floor.usage),
          percent(floor.usageBelowFloor),
        ]),
    ]),
    '',
    'Excluded browsers (no released version supports every required feature):',
    ...(matrix.excluded.length === 0
      ? ['  (none)']
      : table([
          ['  browser', 'latest', 'usage', 'missing'],
          ...matrix.excluded.map(entry => [
            `  ${entry.browser}`,
            entry.latestReleased ?? '-',
            percent(entry.usage),
            entry.missingFeatures.map(feature => `${feature.id}=${feature.support}`).join(', ') ||
              '(no released versions)',
          ]),
        ])),
    '',
    `Browserslist query: ${matrix.query}`,
    '',
    `Measured aggregate global usage: ${percent(matrix.coverage, 4)}`,
    `Target:                          ${percent(matrix.target, 4)}`,
    `Ceiling of the usage dataset:    ${percent(matrix.totalUsage, 4)} (caniuse global data does not sum to 100%)`,
    '',
    ...(matrix.meetsTarget
      ? [
          `PASS: coverage ${percent(matrix.coverage, 4)} meets the ${percent(matrix.target, 0)} target.`,
        ]
      : renderShortfall(matrix)),
  ].join('\n')
}

export type BrowserMatrixArtifact = ReturnType<typeof buildArtifact>

export interface RunReportOptions {
  /** Injected in tests; defaults to the real pinned caniuse-lite/browserslist. */
  readonly data?: SupportData
  readonly features?: readonly RequiredFeature[]
  readonly target?: number
  /** Where `browser-matrix.json` is written. Defaults to this package. */
  readonly packageDir?: string
  /** Where `.browserslistrc` is written. Defaults to the workspace root. */
  readonly repoRoot?: string
  readonly now?: Date
  /** `false` runs the gate without touching the checked-in artifacts. */
  readonly write?: boolean
  readonly log?: (line: string) => void
}

export interface RunReportResult {
  readonly exitCode: number
  readonly matrix: BrowserMatrix
  readonly artifact: BrowserMatrixArtifact
  readonly browserslistrc: string
  readonly report: string
}

export async function runReport(options: RunReportOptions = {}): Promise<RunReportResult> {
  const data = options.data ?? loadSupportData()
  const features = options.features ?? REQUIRED_FEATURES
  const packageDir = options.packageDir ?? fileURLToPath(new URL('..', import.meta.url))
  const repoRoot = options.repoRoot ?? path.resolve(packageDir, '..', '..')
  // eslint-disable-next-line no-console -- stdout is this report's output.
  const log = options.log ?? console.log

  const matrix = computeMatrix(data, {
    featureIds: features.map(feature => feature.id),
    target: options.target ?? COVERAGE_TARGET_PERCENT,
  })
  const meta: ReportMeta = {
    generatedAt: (options.now ?? new Date()).toISOString(),
    caniuseVersion: data.caniuseVersion,
    browserslistVersion: data.browserslistVersion,
  }

  const artifact = buildArtifact(matrix, meta, features)
  const browserslistrc = renderBrowserslistrc(matrix, meta)
  const report = renderReport(matrix, meta, features)

  if (options.write !== false) {
    const artifactPath = path.join(packageDir, ARTIFACT_FILENAME)
    const json = `${JSON.stringify(artifact, null, 2)}\n`
    // The artifact is checked in, so it has to satisfy the repo's Prettier
    // config or `pnpm format:check` fails after every refresh. If Prettier
    // cannot be loaded, plain JSON is written and the gate still runs.
    let formatted: string
    try {
      const prettier = await import('prettier')
      formatted = await prettier.format(json, {
        ...(await prettier.resolveConfig(artifactPath)),
        filepath: artifactPath,
      })
    } catch {
      formatted = json
    }
    await writeFile(artifactPath, formatted, 'utf8')
    await writeFile(path.join(repoRoot, BROWSERSLISTRC_FILENAME), browserslistrc, 'utf8')
    log(`Wrote ${artifactPath}`)
    log(`Wrote ${path.join(repoRoot, BROWSERSLISTRC_FILENAME)}`)
    log('')
  }

  log(report)

  return { exitCode: matrix.meetsTarget ? 0 : 1, matrix, artifact, browserslistrc, report }
}

export async function main(): Promise<number> {
  const { exitCode } = await runReport()
  return exitCode
}
