/**
 * Release gate for the browser support policy: prints the report, writes the checked-in
 * artifacts, and exits non-zero when measured coverage falls below the target.
 */

import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { loadSupportData, type SupportData } from './caniuse.ts'
import { computeMatrix, COVERAGE_TARGET_PERCENT, type BrowserMatrix } from './matrix.ts'
import { REQUIRED_FEATURES, type RequiredFeature } from './required-features.ts'

export const ARTIFACT_FILENAME = 'browser-matrix.json'
export const BROWSERSLISTRC_FILENAME = '.browserslistrc'

export interface ReportMeta {
  readonly generatedAt: string
  readonly caniuseVersion: string
  readonly browserslistVersion: string
}

export interface BrowserMatrixArtifact {
  readonly generatedAt: string
  readonly generatedBy: string
  readonly caniuseLiteVersion: string
  readonly browserslistVersion: string
  readonly coverageTargetPercent: number
  readonly measuredCoveragePercent: number
  readonly meetsTarget: boolean
  readonly dataCeilingPercent: number
  readonly requiredFeatures: readonly RequiredFeature[]
  readonly appliedFeatureIds: readonly string[]
  readonly unresolvedFeatureIds: readonly string[]
  readonly minimumVersions: Readonly<Record<string, string>>
  readonly browserslistQuery: string
  readonly supportedVersionCount: number
  readonly excludedBrowsers: readonly {
    readonly browser: string
    readonly latestReleased: string | null
    readonly usagePercent: number
    readonly missing: readonly { readonly id: string; readonly support: string }[]
  }[]
}

/**
 * The artifact is checked in, so it has to satisfy the repo's Prettier config
 * or `pnpm format:check` would fail after every refresh. Prettier is a
 * devDependency of this package for that reason alone; if it cannot be loaded,
 * plain `JSON.stringify` output is written and the gate still runs.
 */
async function formatJson(value: unknown, filepath: string): Promise<string> {
  const json = `${JSON.stringify(value, null, 2)}\n`
  try {
    const prettier = await import('prettier')
    const config = await prettier.resolveConfig(filepath)
    return await prettier.format(json, { ...config, filepath })
  } catch {
    return json
  }
}

/** Rounds to 4 decimals so the checked-in artifact does not churn on float noise. */
function round(value: number): number {
  return Number(value.toFixed(4))
}

function percent(value: number, digits = 2): string {
  return `${value.toFixed(digits)}%`
}

export function buildArtifact(
  matrix: BrowserMatrix,
  meta: ReportMeta,
  features: readonly RequiredFeature[],
): BrowserMatrixArtifact {
  return {
    generatedAt: meta.generatedAt,
    generatedBy: 'pnpm browser-matrix (tools/browser-matrix)',
    caniuseLiteVersion: meta.caniuseVersion,
    browserslistVersion: meta.browserslistVersion,
    coverageTargetPercent: matrix.target,
    measuredCoveragePercent: round(matrix.coverage),
    meetsTarget: matrix.meetsTarget,
    dataCeilingPercent: round(matrix.totalUsage),
    requiredFeatures: features,
    appliedFeatureIds: matrix.featureIds,
    unresolvedFeatureIds: matrix.unresolvedFeatureIds,
    minimumVersions: Object.fromEntries(matrix.floors.map(floor => [floor.browser, floor.version])),
    browserslistQuery: matrix.query,
    supportedVersionCount: matrix.supportedVersions.length,
    excludedBrowsers: matrix.excluded.map(entry => ({
      browser: entry.browser,
      latestReleased: entry.latestReleased,
      usagePercent: round(entry.usage),
      missing: entry.missingFeatures.map(feature => ({ id: feature.id, support: feature.support })),
    })),
  }
}

export function renderBrowserslistrc(matrix: BrowserMatrix, meta: ReportMeta): string {
  // Each line of a browserslist config is its own query and the lines are
  // OR-ed, so one `>=` floor per browser is exactly the supported union.
  const lines = [
    '# Generated by `pnpm browser-matrix`: the browser support policy.',
    '# DO NOT HAND-EDIT: rerun `pnpm browser-matrix` instead.',
    '#',
    '# These floors are the intersection of the required native features in',
    '# tools/browser-matrix/src/required-features.ts — chiefly CSS @scope, for',
    '# which no fallback ships.',
    `# caniuse-lite ${meta.caniuseVersion} · browserslist ${meta.browserslistVersion}`,
    `# measured aggregate global usage: ${percent(matrix.coverage, 4)} (target ${percent(matrix.target, 0)})`,
    `# generation timestamp and full detail: ${'tools/browser-matrix/' + ARTIFACT_FILENAME}`,
    '',
    ...matrix.floors.map(floor => `${floor.browser} >= ${floor.version}`),
    '',
  ]
  return lines.join('\n')
}

function table(rows: readonly (readonly string[])[]): string[] {
  const widths: number[] = []
  for (const row of rows) {
    row.forEach((cell, index) => {
      widths[index] = Math.max(widths[index] ?? 0, cell.length)
    })
  }
  return rows.map(row =>
    row
      .map((cell, index) => (index === row.length - 1 ? cell : cell.padEnd(widths[index] ?? 0)))
      .join('  ')
      .trimEnd(),
  )
}

export function renderReport(
  matrix: BrowserMatrix,
  meta: ReportMeta,
  features: readonly RequiredFeature[],
): string {
  const out: string[] = []
  out.push('Browser support matrix')
  out.push('')
  out.push(
    ...table([
      ['  caniuse-lite', meta.caniuseVersion],
      ['  browserslist', meta.browserslistVersion],
      ['  generated', meta.generatedAt],
    ]),
  )
  out.push('')
  out.push('Required native features (a browser must fully support every one):')
  out.push(
    ...table(
      features.map(feature => [
        `  ${feature.id}`,
        matrix.unresolvedFeatureIds.includes(feature.id) ? '[UNRESOLVED] ' : '',
        feature.reason,
      ]),
    ),
  )
  if (matrix.unresolvedFeatureIds.length > 0) {
    out.push('')
    out.push(`  ! Not present in caniuse-lite ${meta.caniuseVersion} and therefore NOT applied:`)
    for (const id of matrix.unresolvedFeatureIds) out.push(`    ${id}`)
  }

  out.push('')
  out.push(
    `Supported matrix: ${matrix.floors.length} browsers, ${matrix.supportedVersions.length} released versions`,
  )
  out.push(
    ...table([
      ['  browser', 'floor', 'usage', 'lost below floor'],
      ...[...matrix.floors]
        .sort((a, b) => b.usage - a.usage)
        .map(floor => [
          `  ${floor.browser}`,
          floor.version,
          percent(floor.usage),
          percent(floor.usageBelowFloor),
        ]),
    ]),
  )

  out.push('')
  out.push('Excluded browsers (no released version supports every required feature):')
  if (matrix.excluded.length === 0) {
    out.push('  (none)')
  } else {
    out.push(
      ...table([
        ['  browser', 'latest', 'usage', 'missing'],
        ...matrix.excluded.map(entry => [
          `  ${entry.browser}`,
          entry.latestReleased ?? '-',
          percent(entry.usage),
          entry.missingFeatures.map(feature => `${feature.id}=${feature.support}`).join(', ') ||
            '(no released versions)',
        ]),
      ]),
    )
  }

  out.push('')
  out.push(`Browserslist query: ${matrix.query}`)
  out.push('')
  out.push(`Measured aggregate global usage: ${percent(matrix.coverage, 4)}`)
  out.push(`Target:                          ${percent(matrix.target, 4)}`)
  out.push(
    `Ceiling of the usage dataset:    ${percent(matrix.totalUsage, 4)} (caniuse global data does not sum to 100%)`,
  )
  out.push('')

  if (matrix.meetsTarget) {
    out.push(
      `PASS: coverage ${percent(matrix.coverage, 4)} meets the ${percent(matrix.target, 0)} target.`,
    )
  } else {
    const shortfall = matrix.target - matrix.coverage
    out.push(
      `FAIL: coverage ${percent(matrix.coverage, 4)} is ${percent(shortfall, 4)} short of the ${percent(matrix.target, 0)} target.`,
    )
    out.push('')
    out.push('Where the missing usage sits:')
    const losses = [
      ...matrix.excluded.map(entry => ({
        label: `${entry.browser} (all versions)`,
        usage: entry.usage,
        why:
          entry.missingFeatures.map(feature => `${feature.id}=${feature.support}`).join(', ') ||
          'no released versions in the dataset',
      })),
      ...matrix.floors
        .filter(floor => floor.usageBelowFloor > 0)
        .map(floor => ({
          label: `${floor.browser} < ${floor.version}`,
          usage: floor.usageBelowFloor,
          why: 'released before the required feature floor',
        })),
    ]
      .filter(loss => loss.usage > 0)
      .sort((a, b) => b.usage - a.usage)
    out.push(...table(losses.map(loss => [`  ${loss.label}`, percent(loss.usage), loss.why])))
    out.push('')
    out.push(
      'The feature floor and the coverage target are jointly unsatisfiable on this data. ' +
        'Either the target moves, a fallback ships for the feature that costs the most usage, ' +
        'or the release is gated as-is.',
    )
  }

  return out.join('\n')
}

export interface RunReportOptions {
  /** Injected in tests; defaults to the real pinned caniuse-lite/browserslist. */
  readonly data?: SupportData
  readonly features?: readonly RequiredFeature[]
  readonly target?: number
  /** Where `browser-matrix.json` is written. Defaults to this package. */
  readonly packageDir?: string
  /** Where `.browserslistrc` is written. Defaults to the workspace root. */
  readonly repoRoot?: string
  readonly now?: Date
  /** `false` runs the gate without touching the checked-in artifacts. */
  readonly write?: boolean
  readonly log?: (line: string) => void
}

export interface RunReportResult {
  readonly exitCode: number
  readonly matrix: BrowserMatrix
  readonly artifact: BrowserMatrixArtifact
  readonly browserslistrc: string
  readonly report: string
}

export async function runReport(options: RunReportOptions = {}): Promise<RunReportResult> {
  const data = options.data ?? loadSupportData()
  const features = options.features ?? REQUIRED_FEATURES
  const target = options.target ?? COVERAGE_TARGET_PERCENT
  const packageDir = options.packageDir ?? fileURLToPath(new URL('..', import.meta.url))
  const repoRoot = options.repoRoot ?? path.resolve(packageDir, '..', '..')
  const log = options.log ?? console.log

  const matrix = computeMatrix(data, { featureIds: features.map(feature => feature.id), target })
  const meta: ReportMeta = {
    generatedAt: (options.now ?? new Date()).toISOString(),
    caniuseVersion: data.caniuseVersion,
    browserslistVersion: data.browserslistVersion,
  }

  const artifact = buildArtifact(matrix, meta, features)
  const browserslistrc = renderBrowserslistrc(matrix, meta)
  const report = renderReport(matrix, meta, features)

  if (options.write !== false) {
    const artifactPath = path.join(packageDir, ARTIFACT_FILENAME)
    await writeFile(artifactPath, await formatJson(artifact, artifactPath), 'utf8')
    await writeFile(path.join(repoRoot, BROWSERSLISTRC_FILENAME), browserslistrc, 'utf8')
    log(`Wrote ${artifactPath}`)
    log(`Wrote ${path.join(repoRoot, BROWSERSLISTRC_FILENAME)}`)
    log('')
  }

  log(report)

  return { exitCode: matrix.meetsTarget ? 0 : 1, matrix, artifact, browserslistrc, report }
}

export async function main(): Promise<number> {
  const { exitCode } = await runReport()
  return exitCode
}
