import { mkdtemp, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

import {
  ARTIFACT_FILENAME,
  BROWSERSLISTRC_FILENAME,
  runReport,
  type RunReportOptions,
} from './report.ts'
import { createFakeSupportData, type FakeDataSpec } from './testing.ts'
import type { RequiredFeature } from './required-features.ts'

const features: readonly RequiredFeature[] = [
  { id: 'scope', reason: 'style isolation, no fallback' },
  { id: 'abort', reason: 'lifecycle cancellation' },
]

const spec: FakeDataSpec = {
  caniuseVersion: '1.0.30001810',
  browserslistVersion: '4.29.0',
  browsers: {
    chrome: { released: ['100', '101', '102'], usage: { '100': 5, '101': 20, '102': 60 } },
    oldie: { released: ['8', '9'], usage: { '8': 1, '9': 4 } },
  },
  features: {
    scope: {
      chrome: { '100': 'n', '101': 'y', '102': 'y' },
      oldie: { '8': 'n', '9': 'n' },
    },
    abort: {
      chrome: { '100': 'y', '101': 'y', '102': 'y' },
      oldie: { '8': 'y', '9': 'y' },
    },
  },
}

const data = createFakeSupportData(spec)

function run(overrides: RunReportOptions = {}) {
  return runReport({
    data,
    features,
    now: new Date('2026-01-15T00:00:00.000Z'),
    write: false,
    log: () => {},
    ...overrides,
  })
}

describe('runReport gate', () => {
  it('exits non-zero when measured coverage is below the target', async () => {
    const result = await run({ target: 91 })

    expect(result.matrix.coverage).toBe(80)
    expect(result.exitCode).toBe(1)
    expect(result.artifact.meetsTarget).toBe(false)
    expect(result.report).toContain('FAIL')
    expect(result.report).toContain('11.0000% short')
  })

  it('names the excluded browsers and why, on failure', async () => {
    const { report } = await run({ target: 91 })

    expect(report).toContain('Excluded browsers')
    expect(report).toContain('oldie')
    expect(report).toContain('scope=n')
    // Usage lost to versions below the floor of a *supported* browser is the
    // other half of the shortfall and must be reported too.
    expect(report).toContain('chrome < 101')
  })

  it('exits zero when measured coverage meets the target', async () => {
    const result = await run({ target: 80 })

    expect(result.exitCode).toBe(0)
    expect(result.artifact.meetsTarget).toBe(true)
    expect(result.report).toContain('PASS')
  })

  it('reports an unresolved feature id rather than silently applying it', async () => {
    const { report, artifact } = await run({
      features: [...features, { id: 'mdn-nope', reason: 'does not exist' }],
      target: 80,
    })

    expect(artifact.unresolvedFeatureIds).toEqual(['mdn-nope'])
    expect(artifact.appliedFeatureIds).toEqual(['scope', 'abort'])
    expect(report).toContain('Not present in caniuse-lite 1.0.30001810')
  })
})

describe('artifact', () => {
  it('records the data versions, features, floors, query and measured coverage', async () => {
    const { artifact } = await run({ target: 91 })

    expect(artifact).toMatchObject({
      generatedAt: '2026-01-15T00:00:00.000Z',
      caniuseLiteVersion: '1.0.30001810',
      browserslistVersion: '4.29.0',
      coverageTargetPercent: 91,
      measuredCoveragePercent: 80,
      meetsTarget: false,
      minimumVersions: { chrome: '101' },
      browserslistQuery: 'chrome >= 101',
      supportedVersionCount: 2,
    })
    expect(artifact.requiredFeatures.map(feature => feature.id)).toEqual(['scope', 'abort'])
    expect(artifact.excludedBrowsers).toEqual([
      {
        browser: 'oldie',
        latestReleased: '9',
        usagePercent: 5,
        missing: [{ id: 'scope', support: 'n' }],
      },
    ])
  })
})

describe('.browserslistrc rendering', () => {
  it('carries the generated header and one floor per supported browser', async () => {
    const { browserslistrc } = await run({ target: 91 })

    expect(browserslistrc).toContain('Generated by `pnpm browser-matrix`')
    expect(browserslistrc).toContain('DO NOT HAND-EDIT')
    expect(browserslistrc).toContain('caniuse-lite 1.0.30001810')
    expect(browserslistrc.split('\n').filter(line => !line.startsWith('#') && line !== '')).toEqual(
      ['chrome >= 101'],
    )
  })
})

describe('artifact writing', () => {
  it('writes browser-matrix.json and .browserslistrc to the given directories', async () => {
    const packageDir = await mkdtemp(path.join(tmpdir(), 'browser-matrix-pkg-'))
    const repoRoot = await mkdtemp(path.join(tmpdir(), 'browser-matrix-root-'))

    const result = await run({ target: 91, write: true, packageDir, repoRoot })

    const written = JSON.parse(await readFile(path.join(packageDir, ARTIFACT_FILENAME), 'utf8'))
    expect(written).toEqual(result.artifact)
    expect(await readFile(path.join(repoRoot, BROWSERSLISTRC_FILENAME), 'utf8')).toBe(
      result.browserslistrc,
    )
  })
})
